version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1
  aws-cli: circleci/aws-cli@3.1.3


parameters:
  run-orb-tests:
    type: boolean
    default: false
  global:
    type: boolean
    default: false
  namer-eks:  
    type: boolean
    default: false
  namer-platforms: 
    type: boolean
    default: false
  emea-eks:  
    type: boolean
    default: false
  emea-platforms: 
    type: boolean
    default: false
  japac-eks:  
    type: boolean
    default: false
  japac-platforms: 
    type: boolean
    default: false
  destroy_all:
    type: boolean
    default: false
    description: run tf destroy as pipeline user.

tf_job_defaults: &tf_job_defaults
  #tag: "1.5.1"
  pre-steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
          - "4c:17:59:7f:f3:7d:61:e0:08:6d:b5:b3:cb:8b:ef:c6" # belongs to GH user "ceratf-module-bot", should have read to all ceratf-modules
    - aws-cli/install
    - aws-cli/assume-role-with-web-identity:
        role-arn: "arn:aws:iam::483285841698:role/SolutionsEngineeringEKS"
        role-session-name: "cci-ceratf-deployment-emea-<< pipeline.number >>"
    # We're doing this because BASH_ENV doesn't work with sh, and sh is the shell on the Terraform docker images
    # TODO: Come up with a better solution
    - run:
        name: Create AWS credentials file
        command: |  
          mkdir -p ~/.aws && \
          source $BASH_ENV && \
          cat > ~/.aws/credentials \<<EOF
          [default]
          aws_access_key_id=${AWS_ACCESS_KEY_ID}
          aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}
          aws_session_token=${AWS_SESSION_TOKEN}
          EOF
    - run:
        name: Install Kubectl
        command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod a+x kubectl
            mv kubectl /usr/local/bin

jobs:
  global:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./global
      - terraform/validate:
          path: ./global
      - terraform/plan:
          path: ./global
  
  namer-eks:
    executor: terraform/default
    steps:
      - checkout
      - run: 
          name: namer
          command: |
            echo "run namer"
            
  namer-platforms:
    executor: terraform/default
    steps:
        - run: 
            name: namer platforms
            command: |
              echo "namer platforms"
  
  emea-eks:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./emea-eks
      - terraform/validate:
          path: ./emea-eks
      - terraform/plan:
          path: ./emea-eks
            
  emea-platforms:
    executor: terraform/default
    steps:
        - run: 
            name: emea platforms
            command: |
              echo "emea platforms"
  
  japac-eks:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./japac-eks
      - terraform/validate:
          path: ./japac-eks
      - terraform/plan:
          path: ./japac-eks
            
  japac-platforms:
    executor: terraform/default
    steps:
      - checkout
      - terraform/fmt:
          path: ./japac-platforms
      - terraform/validate:
          path: ./japac-platforms
      - terraform/plan:
          path: ./japac-platforms

workflows:
  global-workflow:
    when: << pipeline.parameters.global >>
    jobs:
      - global:
          context:
             - empty-context #to explicitly generate OIDC token
             - tf-deploy-machine-user-key
          <<: *tf_job_defaults
      # - namer-eks:
      #     requires:
      #       - global
      # - namer-platforms:
      #     requires:
      #       - namer-eks
      - emea-eks:
          context:
            - empty-context
            - tf-deploy-machine-user-key
          requires:
            - global
          <<: *tf_job_defaults
      # - emea-platforms:
      #     requires:
      #       - emea-eks
      # - japac-eks:
      #     requires:
      #       - global
      #     context:
      #        - empty-context #to explicitly generate OIDC token
      #        - tf-deploy-machine-user-key
      #     <<: *tf_job_defaults
      # - japac-platforms:
      #     requires:
      #       - japac-eks
      #     <<: *tf_job_defaults
  
  eks_layer_namer:
    when: 
      and: 
        - not: << pipeline.parameters.global >>
        - equal: [ true, <<pipeline.parameters.namer-eks>> ]
    jobs:
      - namer-eks
      - namer-platforms:
          requires:
            - namer-eks

  platform_layer_namer:
    when:
      and: 
       - not: << pipeline.parameters.global >>
       - not: <<pipeline.parameters.namer-eks>>
       - equal: [ true, <<pipeline.parameters.namer-platforms>> ]
    jobs:
      - namer-platforms
  
  eks_layer_emea:
    when: 
      and: 
        - not: << pipeline.parameters.global >>
        - equal: [ true, <<pipeline.parameters.emea-eks>> ]
    jobs:
      - emea-eks
      - emea-platforms:
          requires:
            - emea-eks

  platform_layer_emea:
    when:
      and: 
       - not: << pipeline.parameters.global >>
       - not: <<pipeline.parameters.emea-eks>>
       - equal: [ true, <<pipeline.parameters.emea-platforms>> ]
    jobs:
      - emea-platforms
  
  eks_layer_japac:
    when: 
      and: 
        - not: << pipeline.parameters.global >>
        - equal: [ true, <<pipeline.parameters.japac-eks>> ]
    jobs:
      - japac-eks
      - japac-platforms:
          requires:
            - japac-eks

  platform_layer_japac:
    when:
      and: 
       - not: << pipeline.parameters.global >>
       - not: <<pipeline.parameters.japac-eks>>
       - not: << pipeline.parameters.destroy_all >>
       - equal: [ true, <<pipeline.parameters.japac-platforms>> ]
    jobs:
      - japac-platforms

    # jobs:
    #   - terraform/fmt:
    #       name: terraform fmt
    #       <<: *tf_job_defaults
    #   - terraform/validate:
    #       name: terraform validate
    #       <<: *tf_job_defaults
    #   - terraform/plan:
    #       name: terraform plan
    #       <<: *tf_job_defaults
    #       requires: 
    #         - terraform fmt
    #         - terraform validate
    #   - terraform/apply:
    #       name: terraform apply
    #       <<: *tf_job_defaults
    #       requires: 
    #         - terraform plan
    #       filters:
    #           branches:
    #               only: 
    #                 - main

# jobs:
#       - terraform/fmt:
#           name: terraform fmt
#           <<: *tf_job_defaults
#       - terraform/validate:
#           name: terraform validate
#           <<: *tf_job_defaults
#       - terraform/plan:
#           name: terraform plan
#           <<: *tf_job_defaults
#           requires: 
#             - terraform fmt
#             - terraform validate
#       - wait_for_approval:
#           type: approval
#           requires:
#             - terraform plan
#           filters:
#               branches:
#                   only: 
#                     - main
#       - terraform/apply:
#           name: terraform apply
#           <<: *tf_job_defaults 
#           pre-steps:
#             - *presteps
#             - run: 
#                 name: Setup Ansible
#                 command: |
#                   #ansible needs a small army of libraries
#                   apk add --update --no-cache python3 gcc python3-dev musl-dev libffi-dev
#                   python3 -m ensurepip
#                   python3 -m pip install uptime-kuma-api
#                   python3 -m pip install ansible
#                   ansible-galaxy collection install lucasheld.uptime_kuma
#           requires: 
#             - wait_for_approval
#           filters:
#               branches:
#                   only: 
#                     - main