version: 2.1

parameters:
  run-orb-tests:
    type: boolean
    default: false
  global:
    type: boolean
    default: false
  namer-eks:  
    type: boolean
    default: false
  namer-platforms: 
    type: boolean
    default: false

jobs:
  global:
    docker:
      - image: cimg/base:2023.06
    resource_class: small
    steps:
      - checkout
      - run: 
          name: run global
          command: |
            echo "global"
  
  namer-eks:
    docker:
      - image: cimg/base:2023.06
    resource_class: small
    steps:
      - checkout
      - run: 
          name: namer
          command: |
            echo "run namer"
            
  namer-platforms:
    docker:
      - image: cimg/base:2023.06
    resource_class: small
    steps:
        - run: 
            name: namer platforms
            command: |
              echo "namer platforms"
      # - run: 
      #     name: trigger API request
      #     command: |
      #       curl --request POST \
      #         --url https://circleci.com/api/v2/project/gh/AwesomeCICD/ceratf-deployment-monorepo/pipeline \
      #         --header "Circle-Token: $CCI_APIKEY" \
      #         --header "content-type: application/json" \
      #         --data '{"parameters":{"run-orb-tests":false}}'

workflows:
  global-workflow:
    when: << pipeline.parameters.global >>
    jobs:
      - global
      - namer-eks:
          requires:
            - global
      - namer-platforms:
          requires:
            - namer-eks
  
  eks_layer:
    when: 
      and: 
        - not: << pipeline.parameters.global >>
        - equal: [ true, <<pipeline.parameters.namer-eks>> ]
    jobs:
      - namer-eks
      - namer-platforms

  platform_layer:
    when:
      and: 
       - not: << pipeline.parameters.global >>
       - not: <<pipeline.parameters.namer-eks>>
       - equal: [ true, <<pipeline.parameters.namer-platforms>> ]
    jobs:
      - namer-platforms
  


  # namer:
  #   jobs:
  #     - namer-eks
  #     - namer-platforms:
  #         requires:
  #           - namer-eks

# version: 2.1

# executors:
#   base:
#     docker:
#       - image: cimg/base:stable

# parameters:
#   global:
#     type: boolean
#     default: false
#   namer:
#     type: boolean
#     default: false
#   emea:
#     type: boolean
#     default: false
#   japac:
#     type: boolean
#     default: false
#   namer-platforms:
#     type: boolean
#     default: false
#   emea-platforms:
#     type: boolean
#     default: false
#   japac-platforms:
#     type: boolean
#     default: false
    
