version: 2.1

parameters:
  run-orb-tests:
    type: boolean
    default: false
  global:
    type: boolean
    default: false
  namer-eks:  
    type: boolean
    default: false
  namer-platforms: 
    type: boolean
    default: false
  emea-eks:  
    type: boolean
    default: false
  emea-platforms: 
    type: boolean
    default: false
  japac-eks:  
    type: boolean
    default: false
  japac-platforms: 
    type: boolean
    default: false

jobs:
  global:
    docker:
      - image: cimg/base:2023.06
    resource_class: small
    steps:
      - checkout
      - run: 
          name: run global
          command: |
            echo "global"
  
  namer-eks:
    docker:
      - image: cimg/base:2023.06
    resource_class: small
    steps:
      - checkout
      - run: 
          name: namer
          command: |
            echo "run namer"
            
  namer-platforms:
    docker:
      - image: cimg/base:2023.06
    resource_class: small
    steps:
        - run: 
            name: namer platforms
            command: |
              echo "namer platforms"
  
  emea-eks:
    docker:
      - image: cimg/base:2023.06
    resource_class: small
    steps:
      - checkout
      - run: 
          name: emea
          command: |
            echo "run emea"
            
  emea-platforms:
    docker:
      - image: cimg/base:2023.06
    resource_class: small
    steps:
        - run: 
            name: emea platforms
            command: |
              echo "emea platforms"
  
  japac-eks:
    docker:
      - image: cimg/base:2023.06
    resource_class: small
    steps:
      - checkout
      - run: 
          name: japac
          command: |
            echo "run japac"
            
  japac-platforms:
    docker:
      - image: cimg/base:2023.06
    resource_class: small
    steps:
        - run: 
            name: japac platforms
            command: |
              echo "japac platforms"

workflows:
  global-workflow:
    when: << pipeline.parameters.global >>
    jobs:
      - global
      - namer-eks:
          requires:
            - global
      - namer-platforms:
          requires:
            - namer-eks
      - emea-eks:
          requires:
            - global
      - emea-platforms:
          requires:
            - emea-eks
      - japac-eks:
          requires:
            - global
      - japac-platforms:
          requires:
            - japac-eks
  
  eks_layer_namer:
    when: 
      and: 
        - not: << pipeline.parameters.global >>
        - equal: [ true, <<pipeline.parameters.namer-eks>> ]
    jobs:
      - namer-eks
      - namer-platforms:
          requires:
            - namer-eks

  platform_layer_namer:
    when:
      and: 
       - not: << pipeline.parameters.global >>
       - not: <<pipeline.parameters.namer-eks>>
       - equal: [ true, <<pipeline.parameters.namer-platforms>> ]
    jobs:
      - namer-platforms
  
  eks_layer_emea:
    when: 
      and: 
        - not: << pipeline.parameters.global >>
        - equal: [ true, <<pipeline.parameters.emea-eks>> ]
    jobs:
      - emea-eks
      - emea-platforms:
          requires:
            - emea-eks

  platform_layer_emea:
    when:
      and: 
       - not: << pipeline.parameters.global >>
       - not: <<pipeline.parameters.emea-eks>>
       - equal: [ true, <<pipeline.parameters.emea-platforms>> ]
    jobs:
      - emea-platforms
  
  eks_layer_japac:
    when: 
      and: 
        - not: << pipeline.parameters.global >>
        - equal: [ true, <<pipeline.parameters.japac-eks>> ]
    jobs:
      - japac-eks
      - japac-platforms:
          requires:
            - japac-eks

  platform_layer_japac:
    when:
      and: 
       - not: << pipeline.parameters.global >>
       - not: <<pipeline.parameters.japac-eks>>
       - equal: [ true, <<pipeline.parameters.japac-platforms>> ]
    jobs:
      - japac-platforms
