version: 2.1

parameters:
  run-orb-tests:
    type: boolean
    default: false

jobs:
  namer-eks:
    docker:
      - image: cimg/base:2023.06
    resource_class: small
    steps:
      - checkout
      - run: 
          name: orb testing job - orb tools/pack and publish
          command: |
            echo "orb testing job"
            
  namer-platforms:
    docker:
      - image: cimg/base:2023.06
    resource_class: small
    steps:
        - run: 
            name: namer platforms
            command: |
              echo "namer platforms"

workflows:
  namer-eks-layer:
    jobs:
      - namer-eks
      - namer-platforms:
          requires:
            - namer-eks